name: Build for macOS

on:
  workflow_dispatch:

jobs:
  Build-for-macOS:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Build App
        run: |
          dotnet publish App.sln --runtime osx-arm64 --self-contained --configuration Release -p:PublishSingleFile=true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-arm64
          path: bin/Release
