name: Compile and Test current Code Base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Dev-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Build App
        run: |
          dotnet publish App.sln --runtime linux-x64 --self-contained --configuration Release -p:PublishSingleFile=true
      - name: Copy test data
        run: |
          cp .tests/* bin/Release/net8.0/linux-x64/publish
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Test with pytest
        run: |
          cd bin/Release/net8.0/linux-x64/publish
          chmod +x App
          pytest tests.py
