name: Test for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Test-for-Windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Copy test data
        run: |
          cp .tests/* .release/windows_x64
      - name: Unzip application
        run: |
          cd .release/windows_x64
          Expand-Archive -Force App.zip .
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Test with pytest
        run: |
          cd .release/windows_x64
          pytest tests.py
